name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types:
      - created

env:
  ESM_NAME: '@openmrs/esm-helloworld-app'
  JS_NAME: 'openmrs-esm-helloworld-app.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run lint
      - run: npm run coverage
      - run: npm run typescript
      - run: npm run build --if-present
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist
